import type { NextPage } from 'next';
import * as React from 'react';
import { useForm } from 'react-hook-form';
import Head from 'next/head';
import { Prisma } from '@prisma/client';

const saveTwit = async (data: Prisma.TwitCreateInput) => {
  await fetch('/api/tweep', {
    method: 'POST',
    body: JSON.stringify(data),
  });
};

const Home: NextPage = () => {
  const { register, handleSubmit } = useForm();

  const onSubmit = async (data: Prisma.TwitCreateInput) => {
    try {
      await saveTwit(data);
    } catch (err) {
      console.error(err);
    }
  };

  return (
    <>
      <Head>
        <title>boring tweeps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="timeline__container">
        <form onSubmit={handleSubmit(onSubmit)}>
          <input
            {...register('body', { required: true })}
            placeholder="What's happening?"
          />
          <div>
            <button>Tweet</button>
          </div>
        </form>
      </div>
    </>
  );
};

export default Home;
