import type { NextPage } from 'next';
import * as React from 'react';
import Head from 'next/head';
import { Prisma } from '@prisma/client';
import { StarSVG } from '../components/StarSVG';
import { TweepeyForm } from '../components/TweetForm';

const saveTwit = async (data: Prisma.TwitCreateInput) => {
  await fetch('/api/tweep', {
    method: 'POST',
    body: JSON.stringify(data),
  });
};

const Home: NextPage = () => {
  const onSubmit = async (data: Prisma.TwitCreateInput) => {
    try {
      await saveTwit(data);
    } catch (err) {
      console.error(err);
    }
  };

  return (
    <div>
      <Head>
        <title>boring tweeps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="timeline__container">
        <div className="timeline__heading">
          <h1 className="timeline__heading--title">home</h1>
          <div className="svg__wrapper">
            <StarSVG />
          </div>
        </div>
        <TweepeyForm onSubmit={onSubmit} />
      </div>
    </div>
  );
};

export default Home;
